spring.application.name=spotify_users

server.port=8080

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/spotify_users}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:2003}
spring.datasource.driver-class-name=org.postgresql.Driver

cloud.service-url=${CLOUD_SERVICE_URL:http://localhost:8083}
music.service-url=${MUSIC_SERVICE_URL:http://localhost:8082}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true