import type { DashboardData } from "@/app/types/dashboard";

export const dashboardMock: DashboardData = {
  userName: "Daan",
  createdFor: [
    { id: "m1", title: "Mix diario 1", subtitle: "… y más", strip: "cyan" },
    { id: "m2", title: "Mix diario 2", subtitle: "… y más", strip: "amber" },
    { id: "m3", title: "Mix diario 3", subtitle: "… y más", strip: "red" },
    { id: "m4", title: "Mix diario 4", subtitle: "… y más", strip: "pink" },
    { id: "m5", title: "Mix diario 5", subtitle: "… y más", strip: "lime" },
  ],
  mostPlayed: [
    { id: "c1", title: "Mix chill", subtitle: "… y más", strip: "lime" },
    { id: "c2", title: "Mix hip hop", subtitle: "… y más", strip: "cyan" },
    { id: "c3", title: "Mix de Ivan Cornejo", subtitle: "… y más", strip: "red" },
    { id: "c4", title: "Mix reggaetón", subtitle: "… y más", strip: "purple" },
    { id: "c5", title: "Mix pop", subtitle: "… y más", strip: "purple" },
  ],
  likedSongs: [
    { id: "s1", title: "Do To Me", artist: "Tim Sanders", album: "Do To Me", added: "hace 1 hora", duration: 145 },
    { id: "s2", title: "Gyalchester", artist: "Drake", album: "More Life", added: "hace 1 hora", duration: 189 },
    { id: "s3", title: "Superpowers", artist: "Daniel Caesar", album: "NEVER ENOUGH", added: "hace 3 horas", duration: 175 },
    { id: "s4", title: "Body", artist: "Don Toliver", album: "OCTANE", added: "hace 3 horas", duration: 156 },
    { id: "s5", title: "Regresen el Tiempo", artist: "La Santa Grifa", album: "Fuera de Órbita", added: "hace 22 horas", duration: 176 },
    { id: "s6", title: "Secondhand (feat. Rema)", artist: "—", album: "OCTANE", added: "hace 1 día", duration: 227 },
  ],

  playlists: [
    {
      id: "p1",
      title: "Noches oscuras",
      subtitle: "Rock industrial y metal",
      icon: "fa-moon",
      songs: [
        {
          id: "p1-s1",
          title: "Sonne",
          artist: "Rammstein",
          album: "Mutter",
          added: "hace 2 días",
          duration: 272,
        },
        {
          id: "p1-s2",
          title: "Du Hast",
          artist: "Rammstein",
          album: "Sehnsucht",
          added: "hace 3 días",
          duration: 234,
        },
        {
          id: "p1-s3",
          title: "Engel",
          artist: "Rammstein",
          album: "Sehnsucht",
          added: "hace 4 días",
          duration: 264,
        },
      ],
    },
    {
      id: "p2",
      title: "Gym mode",
      subtitle: "Energía para entrenar",
      icon: "fa-dumbbell",
      songs: [
        {
          id: "p2-s1",
          title: "Power",
          artist: "Kanye West",
          album: "My Beautiful Dark Twisted Fantasy",
          added: "hace 1 día",
          duration: 292,
        },
        {
          id: "p2-s2",
          title: "Nonstop",
          artist: "Drake",
          album: "Scorpion",
          added: "hace 2 días",
          duration: 238,
        },
        {
          id: "p2-s3",
          title: "FE!N",
          artist: "Travis Scott",
          album: "UTOPIA",
          added: "hace 2 días",
          duration: 191,
        },
      ],
    },
    {
      id: "p3",
      title: "Coding late",
      subtitle: "Música para programar",
      icon: "fa-code",
      songs: [
        {
          id: "p3-s1",
          title: "After Dark",
          artist: "Mr.Kitty",
          album: "Time",
          added: "hace 5 días",
          duration: 257,
        },
        {
          id: "p3-s2",
          title: "Resonance",
          artist: "HOME",
          album: "Odyssey",
          added: "hace 5 días",
          duration: 212,
        },
        {
          id: "p3-s3",
          title: "Memory Reboot",
          artist: "VØJ, Narvent",
          album: "Memory Reboot",
          added: "hace 1 semana",
          duration: 204,
        },
      ],
    },
    {
      id: "p4",
      title: "Flowy mix",
      subtitle: "Hecho para ti",
      icon: "fa-music",
      songs: [
        {
          id: "p4-s1",
          title: "Starboy",
          artist: "The Weeknd",
          album: "Starboy",
          added: "hace 1 hora",
          duration: 230,
        },
        {
          id: "p4-s2",
          title: "LUNA",
          artist: "Feid, ATL Jacob",
          album: "FERXXOCALIPSIS",
          added: "hace 2 horas",
          duration: 196,
        },
        {
          id: "p4-s3",
          title: "One Dance",
          artist: "Drake",
          album: "Views",
          added: "hace 3 horas",
          duration: 174,
        },
      ],
    },
  ],
};