server.port=8080

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

cloudflare.r2.account-id=${CLOUDFLARE_R2_ACCOUNT_ID:}
cloudflare.r2.access-key=${CLOUDFLARE_R2_ACCESS_KEY:}
cloudflare.r2.secret-key=${CLOUDFLARE_R2_SECRET_KEY:}
cloudflare.r2.bucket=${CLOUDFLARE_R2_BUCKET:}
cloudflare.r2.public-base-url=${CLOUDFLARE_R2_PUBLIC_BASE_URL:}


spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=250MB