spring.application.name=spotify_music

server.port=8080

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/spotify_music}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:2003}
spring.datasource.driver-class-name=org.postgresql.Driver

cloud.service-url=${CLOUD_SERVICE_URL:http://localhost:8083}
user.service-url =${USER_SERVICE_URL:http://localhost:8081}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=250MB